### ISSUE TITLE
Guide for deploying on DSM

### ISSUE THREAD

**Issue by ndg86** [alexanderharm/node-carddav2phone#4]
Could you please help me a bit, I am not able to install your application on my Diskstation.
I think a little guide could also help others.

**Comment by alexanderharm** [comment]
Hi, since it works like any other node app I never thought of writing a guide myself. There are so many out there...

In short though:

- Install Node.js from Synology's packet manager
- `git clone` this repo into the shared folder/directory of your choice
- `cd` into the directory and run `npm install`
- create your own `settings.json`
- Use e. g. Synology's task planner to create a periodic task, as command use

```
cd /volumeX/path/to/node-carddav2phone && /usr/local/bin/node dist/index.js
```

Does that point you into the right direction? If that is enough I can happily add that to the read me.

**Comment by ndg86** [comment]
Thank you, that's just what i needed.

**Comment by alexanderharm** [comment]
Does

```
/usr/node-carddav2phone/settings.json
```

exist?

I updated the steps to include the `npm install` command. Forgot that one.

**Comment by ndg86** [comment]
Sorry had some things confused.
I am trying on the DS and a Docker container. Docher node can npm install, but DS gets an error:

```
npm ERR! code ENOENT

npm ERR! syscall open
npm ERR! path /var/services/homes/admin/.npm/_cacache/tmp/c1427261
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/var/services/homes/admin/.npm/_cacache/tmp/c1427261'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Response timeout while trying to fetch https://registry.npmjs.org/comment-json (over 30000ms)`
```

**Comment by alexanderharm** [comment]
Not sure I follow you. Can you describe your setup in detail? What is the Docker container for and why don't you use the builtin Node?

**Comment by ndg86** [comment]
I am using node on the DS. For troubleshooting I am also testing with official Docker node image.
npm install on the DS causes the error which i posted:

> 
> 
> Sorry had some things confused.
> I am trying on the DS and a Docker container. Docher node can npm install, but DS gets an error:
> 
> ```
> npm ERR! code ENOENT
> 
> npm ERR! syscall open
> npm ERR! path /var/services/homes/admin/.npm/_cacache/tmp/c1427261
> npm ERR! errno -2
> npm ERR! enoent ENOENT: no such file or directory, open '/var/services/homes/admin/.npm/_cacache/tmp/c1427261'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> npm ERR! Response timeout while trying to fetch https://registry.npmjs.org/comment-json (over 30000ms)`
> ```

**Comment by alexanderharm** [comment]
Weird, because <https://registry.npmjs.org/comment-json> is accessbile from my network...

**Comment by ndg86** [comment]
Had a little progress, now fighting with errors from import:

```
Already checked for updates today.
CardDAV: creating clients
Error: Bad status: 0
    at exports.XMLHttpRequest.request.onreadystatechange (/usr/node-carddav2phone/node_modules/dav/dav.js:3424:27)
    at exports.XMLHttpRequest.dispatchEvent (/usr/node-carddav2phone/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/node-carddav2phone/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at exports.XMLHttpRequest.handleError (/usr/node-carddav2phone/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
    at ClientRequest.errorHandler (/usr/node-carddav2phone/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at ClientRequest.emit (node:events:378:20)
    at TLSSocket.socketErrorListener (node:_http_client:462:9)
    at TLSSocket.emit (node:events:378:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
10_10_20_3_5001_carddav_Andy_bfbc1017-5039-8767-29ead440: no vcards
CardDAV: no updates available
```
