### ISSUE TITLE
snom error when uploading cfg

### ISSUE THREAD

**Issue by unclesam87** [alexanderharm/node-carddav2phone#8]
i used the updated version of ur script and it runs trough without any problems, but after i upload the new cfg to my snom as u desrcibed i get the following error in the log files: 
`9/2/2023 12:25:40 [NOTICE] PHN: XCAPclient: new etag from server: "63f11f53-2fab7"
19/2/2023 12:25:40 [NOTICE] PHN: XCAPclient: Retrieving directory failed with error-code 4242 and message:`
that i what i change in the config
`xcap_tbook_sync_interval!: 7200
xcap_server_name!: 172.16.20.19
xcap_server_port!: 80
xcap_directory_auid!: /snom/
xcap_dir_doc_name!: snom_xcap_private.xml
xcap_via_tls!: off`

i use an nginx webserver and used the webroot /var/www and dir "snom" so my files are found under: http://[172.16.20.19/snom/users/sipaccount@sipprovider.com/snom_xcap_private.xml
i can open that xml without any problem outside of an snom:)

**Comment by alexanderharm** [comment]
haven't been using xcap myself in a long time. which phone/firmware version are you using?

**Comment by alexanderharm** [comment]
>Please note: Starting version [10.1.119.10](https://service.snom.com/display/wiki/10.1.119.10+Release) XCAP is removed from Snom deskphone firmware and its support is deprecated.

<https://service.snom.com/display/wiki/Directory+-+XCAP>

Maybe you are struck by this?

**Comment by alexanderharm** [comment]
Have you tried using the phonebook directory (just configure the yealink part)?

**Comment by unclesam87** [comment]
now my phone says that the server adressbook is too big, 
i have a pretty old one - an snom 360 with an version 8
adressbook file is 191 kb and has 80 entrys so that cant be the error

**Comment by unclesam87** [comment]
> Have you tried using the phonebook directory (just configure the yealink part)?

i am not tied to xcap when u recommend an different aproach i will try it. but how do i sync my phone with that phonebook?

**Comment by alexanderharm** [comment]
just to be clear:
- your mobile syncs e. g. via CardDAV
- my tool just pulls (NO sync) the data from your CardDAV-Server
- it can then produce xcap, tbook and other formats
- snom can use xcap and tbook

80 entries should be fine. I will test on my end since I made quite a few changes recently. Maybe I broke xcap.

**Comment by unclesam87** [comment]
yes i am using nextcloud over webdav for years now.
And i wanna use ur script excaktly for that - just pulling data.
i change to tbook, generate an xml but im not quite sure how i push that thing to my snom - didnt found any documentation on the web for that procotol

found another "error" - i have to adressbooks in nextcloud and each produces an different webdav adress but when i pull them into ur script i get the contacts of both adressbooks what i in total around 600 contacts (what is still below the 2000 limit of snom phones but yeah a different size)
